production:
  url: redis://redis
  connect_timeout: 0.5
  circuit_breaker:
    error_threshold: 1
    error_timeout: 2

development:
  url: redis://redis
  connect_timeout: 0.5
  circuit_breaker:
    error_threshold: 1
    error_timeout: 2

test:
  url: redis://redis/<%= ENV.fetch('PARALLEL_INDEX', '1') %>
  connect_timeout: 0.5
